yiisoft/db-sqlite

- src/Schema.php
- tests/unit/SchemaTest.php
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | https://github.com/yiisoft/yii2/issues/16897
> SQLite missing PK detection case

- .github/workflows/build.yml
- README.md
- composer.json
| Fixed issues  | https://github.com/yiisoft/db/issues/105
> Fix name badge build, remove cycle dependencies.

- README.md
- composer.json
- phpunit.xml.dist
- tests/BatchQueryResultTest.php
- tests/ColumnSchemaBuilderTest.php
- tests/CommandTest.php
- tests/ConnectionTest.php
- tests/QueryBuilderTest.php
- tests/QueryTest.php
- tests/SchemaTest.php
| Fixed issues  | https://github.com/yiisoft/db/issues/108
> Fix tests.

- phpunit.xml.dist
- tests/BatchQueryResultTest.php
- tests/ColumnSchemaBuilderTest.php
- tests/bootstrap.php
| Fixed issues  | https://github.com/yiisoft/db/issues/108
> Fix visibility property tests.

- src/Command/Command.php
- src/Condition/InConditionBuilder.php
- src/Condition/LikeConditionBuilder.php
- src/Query/QueryBuilder.php
- src/Schema/ColumnSchemaBuilder.php
- src/Schema/Schema.php
- src/Token/BaseTokenizer.php
- src/Token/SqlToken.php
- src/Token/SqlTokenizer.php
- tests/ColumnSchemaBuilderTest.php
- tests/ConnectionTest.php
- tests/QueryBuilderTest.php
| Fixed issues  | https://github.com/yiisoft/db/pull/115
> Improve db-sqlite.

- src/Schema/Schema.php
> Fix schema typehints in db.

- src/Condition/InConditionBuilder.php
- src/Query/QueryBuilder.php
> Fix tests improve querys classes.

- .github/workflows/build.yml
- src/Command/Command.php
- src/Condition/InConditionBuilder.php
- src/Condition/LikeConditionBuilder.php
- src/Query/QueryBuilder.php
- src/Schema/ColumnSchemaBuilder.php
- src/Schema/Schema.php
- tests/ConnectionTest.php
- tests/QueryBuilderTest.php
- tests/QueryTest.php
- tests/SchemaTest.php
> Fix tests change folder plural to singular in db.

- src/Schema/Schema.php
> Fix tests change in columnschema class in db.

- src/Query/QueryBuilder.php
- src/Schema/ColumnSchemaBuilder.php
- src/Schema/Schema.php
- src/Schema/TableSchema.php
- tests/SchemaTest.php
> Rework code.

- src/Schema/ColumnSchemaBuilder.php
- src/Schema/Schema.php
> Fix tests change in db.

- src/Schema/Schema.php
PR related to this issue: https://github.com/yiisoft/arrays/pull/30
> Update namespace for multisort method

- composer.json
- src/Query/QueryBuilder.php
- src/Schema/Schema.php
- src/Token/SqlToken.php
- tests/CommandTest.php
> Enhacements.

- src/Query/QueryBuilder.php
> Fix scrutinizer issues.

- src/Query/QueryBuilder.php
| Fixed issues  | https://github.com/yiisoft/yii2/issues/17960
> Fix unsigned primary key type mapping for SQLite.

- src/Query/QueryBuilder.php
- tests/QueryBuilderTest.php
| Fixed issues  | https://github.com/yiisoft/yii2/pull/17858/files
> Fix issue 17858

- tests/CommandTest.php
> Add tests addforeingkey validation

- .github/workflows/build.yml
- .github/workflows/mutation.yml
- .github/workflows/static.yml
- README.md
- composer.json
> Adjust github actions.

- src/Schema/Schema.php
> Fix typehint schema

- composer.json
- src/BaseTokenizer.php
- src/ColumnSchemaBuilder.php
- src/Command.php
- src/Condition/InConditionBuilder.php
- src/Condition/LikeConditionBuilder.php
- src/Connection.php
- src/QueryBuilder.php
- src/Schema.php
- src/SqlToken.php
- src/SqlTokenizer.php
- src/TableSchema.php
- tests/BatchQueryResultTest.php
- tests/ColumnSchemaBuilderTest.php
- tests/CommandTest.php
- tests/ConnectionTest.php
- tests/Data/sqlite.sql
- tests/QueryBuilderTest.php
- tests/QueryTest.php
- tests/SchemaTest.php
- tests/TestCase.php
> Refactory code and clean-up.

- .github/workflows/build.yml
- .github/workflows/mutation.yml
- .github/workflows/static.yml
- README.md
- composer.json
- src/BaseTokenizer.php
- src/Command.php
- src/Condition/InConditionBuilder.php
- src/Connection.php
- src/QueryBuilder.php
- src/Schema.php
| Fixed issues  | https://github.com/yiisoft/db/pull/182, https://github.com/yiisoft/db/pull/183 tests static analisys will pass when merge `yiisoft/db`.
> Improvements.

- .github/workflows/build.yml
- .github/workflows/mutation.yml
- .github/workflows/static.yml
> Fix minor correction.

- .github/workflows/build.yml
- .github/workflows/mutation.yml
- .github/workflows/static.yml
- .scrutinizer.yml
- composer.json
- src/Schema.php
- tests/ConnectionTest.php
> Update dev dependencies, pipeline and fixed tests.

- .scrutinizer.yml
- README.md
- composer.json
> Update dev dependencies, scrutinizer and README.md.

- src/BaseTokenizer.php
- tests/ConnectionTest.php
- tests/TestCase.php
| Fixed issues  | https://github.com/yiisoft/db/pull/206
> Fix changes cache.

- README.md
- tests/ConnectionTest.php
- tests/TestCase.php
> Update last changes cache.

- composer.json
- src/Connection.php
- src/QueryBuilder.php
- src/Schema.php
- src/SqlToken.php
- tests/ConnectionTest.php
- tests/SchemaTest.php
- tests/TestCase.php
| Issue | https://github.com/yiisoft/db/pull/215
> Draft rework code.

- src/QueryBuilder.php
- tests/TestCase.php
> Fixed tests.

- .scrutinizer.yml
> Fix config scrutinizer.

- tests/CommandTest.php
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any
> fix for test

- tests/CommandTest.php
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any
> fix for test2

- tests/QueryTest.php
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any
> fix for test3

- src/Builder/InConditionBuilder.php
- src/Builder/LikeConditionBuilder.php
- src/PDO/QueryBuilderPDOSqlite.php
| Fixed issues  | https://github.com/yiisoft/db/pull/278
> Fix `query/conditions`.

- src/PDO/CommandPDOSqlite.php
- src/PDO/SchemaPDOSqlite.php
> Pdo 2. Adding insertEx and partial removing usages of pdoStatement

- src/Builder/InConditionBuilder.php
- src/DMLQueryBuilder.php
- src/PDO/CommandPDOSqlite.php
- src/PDO/ConnectionPDOSqlite.php
- src/PDO/QueryBuilderPDOSqlite.php
| Fixed issues  | https://github.com/yiisoft/db/pull/283
> Set error level psalm to 2.

- src/PDO/CommandPDOSqlite.php
> Third step of remove PDO. Using only fetchAll

- src/PDO/CommandPDOSqlite.php
> Step 4. Remove PDO (work with internalQuery)

- src/PDO/CommandPDOSqlite.php
- src/PDO/ConnectionPDOSqlite.php
- src/PDO/SchemaPDOSqlite.php
- tests/ConnectionTest.php
- tests/SchemaTest.php
> Simplification of Connection - removing pool from Connection

- src/PDO/SchemaPDOSqlite.php
> Psalm fixes

- src/PDO/ConnectionPDOSqlite.php
> Common constructor for ConnectionPDO

- src/PDO/CommandPDOSqlite.php
- src/PDO/SchemaPDOSqlite.php
- tests/ConnectionTest.php
- tests/TestCase.php
> Removing getDriver from ConnectionPDO classes

- src/PDO/CommandPDOSqlite.php
- src/PDO/SchemaPDOSqlite.php
> Refactoring lastInsertId

- src/PDO/ConnectionPDOSqlite.php
- src/Schema.php
- tests/ColumnSchemaBuilderTest.php
- tests/QueryBuilderTest.php
> Remove PDO from Schemas

- src/PDO/TransactionPDOSqlite.php
- src/Schema.php
- tests/ConnectionTest.php
> Removing transactionIsolationLevel & operations with savepoint from Schema

- .github/workflows/build.yml
- .github/workflows/mutation.yml
- .github/workflows/static.yml
- .scrutinizer.yml
- src/Schema.php
- tests/CommandTest.php
- tests/QueryTest.php
> Update dependencies workflows.

- src/PDO/CommandPDOSqlite.php
- src/PDO/ConnectionPDOSqlite.php
- src/PDO/TransactionPDOSqlite.php
- tests/TestCase.php
> Move classes `PDO` to directory `src/Driver/PDO`.

- src/DDLQueryBuilder.php
- src/DMLQueryBuilder.php
- src/DQLQueryBuilder.php
- src/PDO/ConnectionPDOSqlite.php
- src/PDO/QueryBuilderPDOSqlite.php
- tests/QueryBuilderTest.php
> QueryBuilder refactoring

- src/DDLQueryBuilder.php
- src/DMLQueryBuilder.php
- src/DQLQueryBuilder.php
- src/PDO/CommandPDOSqlite.php
- src/PDO/QueryBuilderPDOSqlite.php
> Use injection dependencies, remove dependencie transitive.

- src/DDLQueryBuilder.php
- src/DMLQueryBuilder.php
- tests/SchemaTest.php
> Refactoring createIndex and more cleanup of code

- src/PDO/ConnectionPDOSqlite.php
- src/PDO/PDODriver.php
- tests/ConnectionTest.php
- tests/TestCase.php
> Work with attributes on connection

- src/PDO/PDODriver.php
- tests/CommandTest.php
- tests/QueryTest.php
> fix for php81

- src/Builder/InConditionBuilder.php
- src/DQLQueryBuilder.php
> Usage QueryInterface

- src/PDO/ConnectionPDOSqlite.php
> Unused check of exists constant

- src/CommandPDO.php
- src/ConnectionPDO.php
- src/PDODriver.php
- src/QueryBuilder.php
- src/TransactionPDO.php
- tests/TestCase.php
> Remove `PDO` folders in subpackages

- composer.json
- tests/ConnectionTest.php
> Apply last changes `yiisoft/db`.

- tests/CommandTest.php
- tests/Provider/QueryBuilderProvider.php
- tests/QueryBuilderTest.php
> Refactoring of batchInsert (for remove using of Quoter)

- composer.json
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any
> Fix for cache in tests

- src/DMLQueryBuilder.php
- tests/Provider/CommandProvider.php
- tests/Provider/QueryBuilderProvider.php
> Normalize column names

- composer.json
- src/CommandPDO.php
> Remove yiisoft/strings

- src/Builder/InConditionBuilder.php
- tests/Provider/QueryBuilderProvider.php
https://github.com/yiisoft/yii2/pull/19152
> Allow expression in IN builder for columns

- tests/Provider/SchemaProvider.php
| Fixed issues  | https://github.com/yiisoft/db/issues/264
> Fix for typecast decimal columns

- src/DQLQueryBuilder.php
- tests/QueryBuilderTest.php
| Fixed issues  | https://github.com/yiisoft/db/pull/685
> Fix method names

- .github/workflows/rector.yml
> Update rector workflow.

- docs/pt-BR/testing.md
> translation into Brazilian Portuguese

- tests/CommandTest.php
> Update test according to main PR

- tests/CommandTest.php
- tests/Provider/CommandProvider.php
- tests/QueryBuilderTest.php
> Update tests according to the main PR

- composer.json
- src/SqlToken.php
> Revert rector changes

- CHANGELOG.md
- src/Builder/JsonOverlapsConditionBuilder.php
- src/DQLQueryBuilder.php
- tests/QueryBuilderTest.php
- tests/Support/Fixture/sqlite.sql
- yiisoft/db#855
| Fixed issues  | yiisoft/active-record#362
> Add json overlaps condition builder

- CHANGELOG.md
- src/Schema.php
- tests/Provider/SchemaProvider.php
| Fixed issues  | yiisoft/db#860
> Update `bit` type

- CHANGELOG.md
- src/Column.php
- src/Column/ColumnFactory.php
- src/QueryBuilder.php
- src/Schema.php
- tests/CommandTest.php
- tests/Provider/ColumnFactoryProvider.php
- tests/Provider/ColumnSchemaBuilderProvider.php
- tests/QueryBuilderTest.php
- yiisoft/db#877
| Fixed issues  | yiisoft/db#854
> Separate column type constants

- CHANGELOG.md
- src/Dsn.php
> Refactor `Dsn` class

- CHANGELOG.md
- src/Column/ColumnFactory.php
- src/Schema.php
- tests/ColumnFactoryTest.php
- tests/Provider/ColumnFactoryProvider.php
- https://github.com/yiisoft/db/pull/898
> Refactor normalizeDefaultValue()

- CHANGELOG.md
- src/Connection.php
- src/QueryBuilder.php
- tests/CommandTest.php
- https://github.com/yiisoft/db/pull/906
> Update according to changes in `db`

- CHANGELOG.md
- src/AbstractTokenizer.php
- src/Connection.php
- src/DDLQueryBuilder.php
- src/DMLQueryBuilder.php
- src/SqlToken.php
> Explicitly mark nullable parameters

- .github/workflows/bc.yml_
- .github/workflows/build.yml
- .github/workflows/composer-require-checker.yml
- .github/workflows/mutation.yml
- .github/workflows/rector.yml
- .github/workflows/static.yml
- CHANGELOG.md
- README.md
- composer.json
- psalm.xml
- src/Command.php
- https://github.com/yiisoft/db/pull/911
> Test PHP 8.4

- CHANGELOG.md
- src/Builder/InConditionBuilder.php
- src/Connection.php
- src/QueryBuilder.php
- src/Schema.php
- tests/ConnectionTest.php
- tests/SchemaTest.php
according to changes in main `db` package
- https://github.com/yiisoft/db/pull/940
> Refactoring

- CHANGELOG.md
- src/DQLQueryBuilder.php
- tests/QueryBuilderTest.php
Related to https://github.com/yiisoft/db/pull/967
> Add `FOR` clause for query

- CHANGELOG.md
- src/Connection.php
- src/Schema.php
- tests/Provider/QueryBuilderProvider.php
- tests/QueryBuilderTest.php
- https://github.com/yiisoft/db/pull/986
- https://github.com/yiisoft/active-record/pull/430
| Fixed issues  | #306
> Replace SQLite quotes from ` to "

- CHANGELOG.md
- src/Schema.php
- tests/Provider/SchemaProvider.php
- https://github.com/yiisoft/db/pull/981
> Refactor constraints

- tests/Provider/QueryBuilderProvider.php
Related to https://github.com/yiisoft/db/pull/1007
> Adapt to changes in Yii DB

- CHANGELOG.md
- src/Column/ColumnDefinitionBuilder.php
- tests/Provider/QueryBuilderProvider.php
- https://github.com/yiisoft/db/pull/1020
> Support column's collation

- tests/Support/TestTrait.php
- https://github.com/yiisoft/db/pull/1022
> Add `replaceQuotes()` to `TestTrait`

- src/Builder/LikeBuilder.php
- src/DQLQueryBuilder.php
Related to https://github.com/yiisoft/db/pull/1023
> Adapt to split Like condition in Yii DB

- CHANGELOG.md
- src/Builder/JsonOverlapsBuilder.php
- tests/QueryBuilderTest.php
| Fixed issues  | 
- https://github.com/yiisoft/db/pull/1054
> Adapt for changes in `db`

- README.md
> Add doc about required caching library
