tests/ConnectionTest.php, tests/TestCase.php
=> Fixed test.

tests/QueryBuilderTest.php, tests/Support/Fixture/sqlite.sql
=> Add insertEx additional test + bugfix for oracle

tests/ConnectionTest.php
=> fix tests for remove Profiler

tests/ConnectionTest.php
=> Logger mock

CHANGELOG.md, src/Schema.php, tests/Provider/SchemaProvider.php, tests/Support/Fixture/sqlite.sql
=> Refactoring of `Schema::normalizeDefaultValue()` method

tests/ColumnSchemaTest.php, tests/Provider/SchemaProvider.php, tests/Support/Fixture/sqlite.sql
=> Add ColumnSchemaTest

tests/PdoConnectionTest.php
=> Fix test group

psalm.xml, src/Command.php
=> Fix psalm error

src/Schema.php
=> Update psalm types

tests/QueryBuilderTest.php
Update tests according to yiisoft/db#761
=> Fix CTE query expressions

CHANGELOG.md, src/DMLQueryBuilder.php, src/Schema.php, tests/Provider/QueryBuilderProvider.php, tests/QueryBuilderTest.php
=> Refactor DMLQueryBuilder

CHANGELOG.md, src/AbstractTokenizer.php, src/Builder/JsonExpressionBuilder.php, src/Command.php, src/DMLQueryBuilder.php, src/DQLQueryBuilder.php, src/QueryBuilder.php, src/Schema.php
=> Remove unused code in `Command` class + Cleanup psalm annotations

CHANGELOG.md, src/Schema.php, tests/QueryBuilderTest.php
**Related with yiisoft/db#789**
=> Fix `QueryBuilderTest::testBatchInsert()`

.github/workflows/static.yml, CHANGELOG.md, composer.json, psalm.xml, psalm4.xml, src/DDLQueryBuilder.php, src/Schema.php, tests/SchemaTest.php
=> Fix psalm issues

CHANGELOG.md, composer.json, rector.php, src/Builder/ExpressionBuilder.php, src/DQLQueryBuilder.php, src/SqlParser.php, tests/CommandTest.php, tests/Provider/SqlParserProvider.php, tests/QueryBuilderTest.php, tests/SqlParserTest.php
=> Update test according to main PR

CHANGELOG.md, src/Column/ColumnDefinitionBuilder.php, src/Column/ColumnFactory.php, src/Connection.php, src/QueryBuilder.php, src/Schema.php, tests/ConnectionTest.php, tests/Provider/QueryBuilderProvider.php, tests/QueryBuilderTest.php, tests/SchemaTest.php
- https://github.com/yiisoft/db/pull/883
=> Add `ColumnDefinitionBuilder`

CHANGELOG.md, composer.json, src/Connection.php
=> Set more specific result type in `Connection` methods

CHANGELOG.md, src/Column/ColumnFactory.php, src/Schema.php, tests/Provider/SchemaProvider.php
- https://github.com/yiisoft/db/pull/897
=> Refactor `ColumnFactory`

CHANGELOG.md, src/QueryBuilder.php, src/Schema.php, tests/Provider/QueryBuilderProvider.php, tests/QueryBuilderTest.php
- https://github.com/yiisoft/db/pull/902
=> Add `QueryBuilder::prepareBinary()` method

CHANGELOG.md, src/Column/ColumnDefinitionBuilder.php, src/Column/ColumnFactory.php, src/DDLQueryBuilder.php, src/Schema.php, tests/ColumnTest.php, tests/Provider/ColumnFactoryProvider.php, tests/QueryBuilderTest.php, tests/SchemaTest.php
- https://github.com/yiisoft/db/pull/917
=> Rename `ColumnSchemaInterface` to `ColumnInterface`

CHANGELOG.md, src/Connection.php, src/Schema.php, tests/QueryBuilderTest.php
- https://github.com/yiisoft/db/pull/943
=> Remove `getCacheKey()` and `getCacheTag()` from `Schema`

src/Command.php, tests/PdoConnectionTest.php
Related to https://github.com/yiisoft/db/pull/965
=> Rename `getLastInsertID()` method in `ConnectionInterface` to `getLastInsertId()`

CHANGELOG.md, src/Column/ColumnDefinitionBuilder.php, src/Column/ColumnFactory.php, tests/ColumnTest.php, tests/Provider/ColumnFactoryProvider.php, tests/Provider/SchemaProvider.php, tests/Support/Fixture/sqlite.sql
- https://github.com/yiisoft/db/pull/968
=> Use `DateTimeColumn`

CHANGELOG.md, src/Command.php, src/DMLQueryBuilder.php, tests/Provider/QueryBuilderProvider.php, tests/QueryBuilderTest.php, tests/Support/Fixture/sqlite.sql
- https://github.com/yiisoft/db/pull/973
=> Implement `DMLQueryBuilder::upsertWithReturningPks()` method

CHANGELOG.md, phpunit.xml.dist, src/Command.php, src/DMLQueryBuilder.php, tests/CommandTest.php, tests/Provider/QueryBuilderProvider.php, tests/QueryBuilderTest.php
- https://github.com/yiisoft/db/pull/976
=> Replace `upsertWithReturningPks()` with `upsertWithReturning()` in `DMLQueryBuilder` class

CHANGELOG.md, src/Schema.php, tests/Provider/SchemaProvider.php, tests/SchemaTest.php
- https://github.com/yiisoft/db/pull/1004
=> Update according changes in `db` package

CHANGELOG.md, tests/CommandTest.php, tests/QueryBuilderTest.php
| Fixed issues  | yiisoft/db#94
=> Adapt to db changes
